-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingJson" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "healthProfileJson" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "checklistJson" JSONB;
